<?php
    $username = $_POST['username'] ?? '';
    $password = $_POST['password'] ?? '';

    $csvPath = '../csv/users.csv';
    
    if (empty($sender) || empty($weight))
        echo "Error: Both sender and weight fields are required!";

    if ($username && $password) {
        if (($handle = fopen($csvPath, 'r')) !== FALSE) {
            $authenticated = false;
            while (($data = fgetcsv($handle, 0, ',', '"', '\\')) !== FALSE) {
                if ($data[0] === $username && $data[1] === $password) {
                    $authenticated = true;
                    break;
                }
            }
            fclose($handle);
        }
    }

    echo "<html>";
    echo "<head>";
    echo "<meta charset='utf-8' />";
    echo "<style>";
    echo "body {";
    echo "display: flex;";
    echo "justify-content: center;";
    echo "align-items: center;";
    echo "min-height: 100vh;";
    echo "padding: 24px;";
    echo "position: relative;";
    echo "background: linear-gradient(";
    echo "237deg,";
    echo "rgba(184, 255, 220, 1) 0%,";
    echo "rgba(130, 139, 255, 1) 100%";
    echo ");";
    echo "}";
    echo ".card {";
    echo "display: flex;";
    echo "flex-direction: column;";
    echo "width: 100%;";
    echo "max-width: 520px;";
    echo "gap: 32px;";
    echo "background-color: #ffffff;";
    echo "border-radius: 16px;";
    echo "padding: 72px clamp(24px, 5vw, 48px);";
    echo "}";
    echo ".desc {";
    echo "gap: 12px;";
    echo "display: flex;";
    echo "flex-direction: column;";
    echo "align-items: flex-start;";
    echo "position: relative;";
    echo "align-self: stretch;";
    echo "width: 100%;";
    echo "flex: 0 0 auto;";
    echo "}";
    echo "h1, p {";
    echo "margin: 0;";
    echo "}";
    echo "h1 {";
    echo "position: relative;";
    echo "align-self: stretch;";
    echo "font-family: 'Inter-Bold', Helvetica;";
    echo "font-weight: 700;";
    echo "color: #4d1799;";
    echo "font-size: 36px;";
    echo "text-align: center;";
    echo "letter-spacing: 0;";
    echo "line-height: normal;";
    echo "}";
    echo "p {";
    echo "position: relative;";
    echo "align-self: stretch;";
    echo "font-family: 'Inter-Regular', Helvetica;";
    echo "font-weight: 400;";
    echo "color: #4d1799;";
    echo "font-size: 24px;";
    echo "text-align: center;";
    echo "letter-spacing: 0;";
    echo "line-height: normal;";
    echo "}";
    echo ".input-field-group {";
    echo "display: flex;";
    echo "flex-direction: column;";
    echo "align-items: flex-start;";
    echo "justify-content: center;";
    echo "gap: 16px;";
    echo "position: relative;";
    echo "align-self: stretch;";
    echo "width: 100%;";
    echo "flex: 0 0 auto;";
    echo "}";
    echo ".input-field {";
    echo "display: flex;";
    echo "height: 54px;";
    echo "align-items: center;";
    echo "padding: 4px 16px;";
    echo "position: relative;";
    echo "align-self: stretch;";
    echo "border-radius: 12px;";
    echo "border: 1px solid;";
    echo "border-color: #aeaeae;";
    echo "}";
    echo ".input-text-wrapper {";
    echo "border: none;";
    echo "width: 100%;";
    echo "background: transparent;";
    echo "position: relative;";
    echo "color: #5f48f9;";
    echo "text-align: left;";
    echo "font-family: 'Inter-Regular', Helvetica;";
    echo "font-weight: 100;";
    echo "font-size: 18px;";
    echo "letter-spacing: 0;";
    echo "line-height: normal;";
    echo "}";
    echo ".input-text-wrapper::placeholder {";
    echo "color: #c2b3ce;";
    echo "opacity: 1;";
    echo "}";
    echo ".input-text-wrapper:focus {";
    echo "outline: none;";
    echo "}";
    echo ".input-field:focus-within {";
    echo "border-color: #717bff;";
    echo "box-shadow: 0 0 0 2px rgba(113, 123, 255, 0.2);";
    echo "}";
    echo ".navigation {";
    echo "display: flex;";
    echo "flex-wrap: wrap;";
    echo "padding-top: 16px;";
    echo "align-items: flex-end;";
    echo "justify-content: center;";
    echo "gap: 8px 8px;";
    echo "position: relative;";
    echo "align-self: stretch;";
    echo "width: 100%;";
    echo "flex: 0 0 auto;";
    echo "}";
    echo ".button-text {";
    echo "position: relative;";
    echo "width: fit-content;";
    echo "font-family: 'Inter-Bold', Helvetica;";
    echo "font-weight: 700;";
    echo "color: #ffffff;";
    echo "font-size: 18px;";
    echo "text-align: center;";
    echo "letter-spacing: 0;";
    echo "line-height: normal;";
    echo "}";
    echo ".btn {";
    echo "all: unset;";
    echo "display: inline-flex;";
    echo "align-items: center;";
    echo "justify-content: center;";
    echo "gap: 10px;";
    echo "padding: 14px 16px;";
    echo "position: relative;";
    echo "flex: 0 0 auto;";
    echo "border-radius: 8px;";
    echo "cursor: pointer;";
    echo "transition: background-color 0.2s ease;";
    echo "}";
    echo ".btn-primary {";
    echo "background-color: #717bff;";
    echo "}";
    echo ".btn-secondary {";
    echo "background-color: #86c7da;";
    echo "}";
    echo ".btn-primary:hover {";
    echo "background-color: #5a66e6;";
    echo "}";
    echo ".btn-primary:active {";
    echo "background-color: #a05aeb;";
    echo "}";
    echo ".btn-primary:focus-visible {";
    echo "outline: 2px solid #4a90e2;";
    echo "outline-offset: 2px;";
    echo "}";
    echo ".btn-secondary:hover {";
    echo "background-color: #6fb3c9;";
    echo "}";
    echo ".btn-secondary:active {";
    echo "background-color: #5a9fb8;";
    echo "}";
    echo ".btn-secondary:focus-visible {";
    echo "outline: 2px solid #4a90e2;";
    echo "outline-offset: 2px;";
    echo "}";
    echo ".visually-hidden {";
    echo "position: absolute;";
    echo "width: 1px;";
    echo "height: 1px;";
    echo "padding: 0;";
    echo "margin: -1px;";
    echo "overflow: hidden;";
    echo "clip: rect(0, 0, 0, 0);";
    echo "white-space: nowrap;";
    echo "border-width: 0;";
    echo "}";
    echo ".error {";
    echo "color: #f38265;";
    echo "text-align: left;";
    echo "font-family: 'Inter-Regular', Helvetica;";
    echo "font-size: 14px;";
    echo "}";
    echo ".error.active {";
    echo "display: inline;";
    echo "}";
    echo "</style>";
    if ($authenticated) {
        echo "<title>Welcome back</title>";
        echo "</head>";
        echo "<body>";
        echo "<section class='card'>";
        echo "<header class='desc'>";
        echo "<h1>Login Success</h1>";
        echo "<p>Welcome " . htmlspecialchars($username) . "! (づ ◕‿◕ )づ</p>";
        echo "</header>";
        echo "<div class='navigation'>";
        echo "<a href='/' class='btn btn-primary'>";
        echo "<span class='button-text'>Back to Home</span>";
        echo "</a>";
        echo "</div>";
        echo "</section></body></html>";
    } else {
        $message = "Error: Invalid username or password.";
        // echo "<html><body>";
        // echo "<h1>Log In</h1>";
        // echo "<p style=\"color:red;\">" . htmlspecialchars($message) . "</p>";
        // echo "<form action=\"/cgi-bin/logIn.php\" method=\"post\">";
        // echo "<label for=\"username\">Username:</label>";
        // echo "<input type=\"text\" id=\"username\" name=\"username\" required><br><br>";
        // echo "<label for=\"password\">Password:</label>";
        // echo "<input type=\"password\" id=\"password\" name=\"password\" required><br><br>";
        // echo "<button type=\"submit\">Log In</button>";
        // echo "</form>";
        // echo "</body></html>";

        echo "<title>Login</title>";
        echo "</head>";
        echo "<body>";
        echo "<section class='card'>";
        echo "<header class='desc'>";
        echo "<h1>Login</h1>";
        echo "<p>Welcome back!</p>";
        echo "</header>";

        echo "<form class='input-field-group' action=\"/cgi-bin/logIn.php\" method=\"post\">";
        echo "<div class='input-field'>";
        echo "<label for='username' class='visually-hidden'>username</label>";
        echo "<input ";
        echo "type='text'";
        echo "id='username'";
        echo "class='input-text-wrapper'";
        echo "placeholder='Username'";
        echo "name='username'";
        echo "required";
        echo "aria-required='true'";
        echo "/>";
        echo "</div>";
        echo "<div class='input-field'>";
        echo "<label for='password' class='visually-hidden'>Email</label>";
        echo "<input ";
        echo "type='password'";
        echo "id='password'";
        echo "class='input-text-wrapper'";
        echo "placeholder='Password'";
        echo "name='password'";
        echo "required";
        echo "aria-required='true'";
        echo "/>";
        echo "</div>";

        echo "<span class='error'>Invalid username or password</span>";
        echo "<div class='navigation'>";

        echo "<button type='submit' class='btn btn-primary'>";
        echo "<span class='button-text'>Login</span>";
        echo "</button>";
        echo "<a href='/' class='btn btn-secondary'>";
        echo "<span class='button-text'>Back to Home</span>";
        echo "</a>";
        echo "</div>";
        echo "</form>";
        echo "</section></body></html>";
    }
    exit();
?>