import csv, os

# view submission by form
# -----------------------------------------------------

# Save data to CSV file
csv_dir = "www/csv" 
csv_path = os.path.join(csv_dir, "submissions.csv")

# Read all submissions
submissions = []
with open(csv_path, "r") as csvfile:
    reader = csv.reader(csvfile)
    for row in reader:
        submissions.append(row)

# view prize pool
# print('<table border="1">')
# print("<tr><th>Name</th><th>Email</th><th>Age</th></tr>")
# for name, email, age in submissions:
#     print(f"<tr><td>{name}</td><td>{email}</td><td>{age}</td></tr>")
# print('</table><br>')
# print()
# print('<a href="/form">Submit another response</a><br>')
# print("</body></html>")

# Print CGI headers ----------------------------------------------------------------
print(f"Status: 200 OK")
print("Content-Type: text/html")
print() # This blank line is CRITICAL

print("<html>")
print("<head>")
print("<meta charset='UTF-8'>")
print("<title>Prize Pool</title>")
print("<style>")
print("body {")
print("display: flex;")
print("justify-content: center;")
print("align-items: center;")
print("min-height: 100vh;")
print("padding: 24px;")
print("position: relative;")
print("background: linear-gradient(")
print("237deg,")
print("rgba(184, 255, 220, 1) 0%,")
print("rgba(130, 139, 255, 1) 100%")
print(");")
print("}")
print("a {")
print("text-decoration: none;")
print("}")
print("p {")
print("font-family: 'Inter-Regular', Helvetica;")
print("font-weight: 400;")
print("color: #9999ad;")
print("font-size: 18px;")
print("}")
print("h1 {")
print("position: relative;")
print("align-self: stretch;")
print("font-family: 'Inter-Bold', Helvetica;")
print("font-weight: 700;")
print("color: #ffffff;")
print("font-size: 36px;")
print("text-align: center;")
print("margin: 0;")
print("}")
print(".card {")
print("display: flex;")
print("flex-direction: column;")
print("width: 100%;")
print("max-width: 700px;")
print("gap: 24px;")
print("}")
print(".navigation {")
print("display: flex;")
print("margin-top: auto;")
print("flex-wrap: wrap;")
print("gap: 8px 16px;")
print("position: relative;")
print("align-self: stretch;")
print("width: 100%;")
print("justify-content: center;")
print("}")
print(".svg-icon {")
print("fill: #b8b8d6;")
print("transition: fill 0.3s ease;")
print("width: 24px;")
print("height: 100%;")
print("}")
print(".svg-icon:hover {")
print("fill: #727BFF;")
print("}")
print(".button-text {")
print("position: relative;")
print("width: fit-content;")
print("font-family: 'Inter-Bold', Helvetica;")
print("font-weight: 700;")
print("color: #ffffff;")
print("text-align: center;")
print("}")
print(".button-text-small {")
print("font-size: 14px;")
print("}")
print(".button-text-big {")
print("font-size: 18px;")
print("}")
print(".btn {")
print("border: none;")
print("display: inline-flex;")
print("align-items: center;")
print("justify-content: center;")
print("gap: 10px;")
print("padding: 12px 12px;")
print("position: relative;")
print("flex: 0 0 auto;")
print("border-radius: 8px;")
print("}")
print(".btn-primary {")
print("background-color: #727BFF;")
print("}")
print(".btn-home {")
print("background-color: #43bccf;")
print("}")
print(".btn-secondary {")
print("background-color: #FFA33B;")
print("}")
print(".btn-primary:hover,")
print(".btn-home:hover,")
print(".btn-secondary:hover {")
print("background-color: #5064FF;")
print("transform: translateY(-1px);")
print("}")
print(".btn-secondary:hover {")
print("background-color: #FF7171;")
print("}")
print(".btn-home:hover {")
print("background-color: #2EB5CA;")
print("}")
print(".table-container {")
print("background-color: #ffffff;")
print("border-radius: 80px 12px;")
print("padding: clamp(16px, 5vw, 24px);")
print("}")
print(".styled-table {")
print("width: 100%;")
print("font-family: 'Inter-Bold', Helvetica;")
print("font-weight: 500;")
print("margin-bottom: 0px;")
print("text-align: center;")
print("table-layout: fixed;")
print("}")
print(".styled-table th, .styled-table td {")
print("padding: 10px;")
print("}")
print(".styled-table th {")
print("color: #b8b8d6;")
print("font-weight: 500;")
print("}")
print(".styled-table td {")
print("color: #727BFF;")
print("}")
print(".styled-table tbody tr:hover {")
print("background-color: #f3ffe5;")
print("}")
print(".visually-hidden {")
print("position: absolute;")
print("width: 1px;")
print("height: 1px;")
print("padding: 0;")
print("overflow: hidden;")
print("clip: rect(0, 0, 0, 0);")
print("white-space: nowrap;")
print("border-width: 0;")
print("}")
print("</style>")
print("</head>")

print("<body>")
print("<div class='card'>")
print("<h1>Prize Pool</h1>")
print("<div class='table-container'>")
print("<table class='styled-table'>")
print("<thead>")
print("<tr>")
print("<th>Name</th>")
print("<th>Email</th>")
print("<th>Age</th>")
print("</tr>")
print("</thead>")
print("<tbody>")

# loop print
for name, email, age in submissions:
    print("<tr>")
    print(f"<td>{name}</td>")
    print(f"<td>{email}</td>")
    print(f"<td>{age}</td>")
    print("</tr>")

print("</tbody>")
print("</table>")
print("</div>")
print("<div class='navigation'>")
print("<a href='/form' class='btn btn-primary'>")
print("<span class='button-text button-text-big'>Fill Another Form</span>")
print("</a>")
print("<a href='/index' class='btn btn-home'>")
print("<span class='button-text button-text-big'>Back to Home</span>")
print("</a>")
print("</div>")
print("</div>")
print("</body>")

print("</html>")
