server {
    listen localhost:8081;
    server_name localhost;
    root www;
    index index.html;
    client_max_body_size 30000000;
    # autoindex on;

	error_page 400 /error/400.html;
	error_page 403 /error/403.html;
	error_page 404 /error/404.html;
	error_page 405 /error/405.html;
	error_page 411 /error/411.html;
	error_page 413 /error/413.html;
	error_page 500 /error/500.html;
	error_page 502 /error/502.html;
	error_page 503 /error/503.html;

    location / {
        allowed_methods GET;
        index index.html;
    }

    location /form {
		allowed_methods GET POST;
        alias www/html;
        index form.html;
    }

    location /images/ {
        allowed_methods GET;
		alias www/asset/img;
		autoindex on;
		# autoindex off;
    }

	location /upload {
		allowed_methods GET POST;
		alias www/html;
		index upload.html;
		client_max_body_size 30;
	}

	location /uploads {
		allowed_methods GET;
	}

	location /fruits {
		allowed_methods GET;
		alias www/html/;
		index fruits.html;
	}

	location /42 {
        return 302 https://42kl.edu.my/;
    }

	location /try/ {
		autoindex off; 
	}

	location /cgi-bin/ {
		allowed_methods GET POST DELETE;
        alias www/cgi/;
        cgi_handler .py /usr/bin/python3;
		# cgi_handler .php /usr/bin/php;
		cgi_handler .php /opt/homebrew/bin/php-cgi;
		client_max_body_size 30;	#test for 413
    }
}