server {
    listen localhost:9743;
    server_name localhost local;
    root ./www;
    index index.html;
    client_max_body_size 30000000;
    autoindex off;

    location / {
        allowed_methods GET;
        index index.html;
    }

    location /assets/ {
        allowed_methods GET;
        autoindex on;
    }

    location /html/ {
        allowed_methods GET;
        autoindex on;
    }

    location /img/ {
        allowed_methods GET;
        autoindex off;
    }
}

server {
    listen localhost:8080;
    server_name example;
    root ./www;
    index index.html;
    client_max_body_size 300000000;
    autoindex off;
    error_page 404 /errors/404.html;

    location / {
        allowed_methods GET;
        index index.html;
		client_max_body_size 345456789;
    }

    location /assets/ {
        allowed_methods GET;
        autoindex on;
    }

    location /html/ {
        allowed_methods GET;
        autoindex on;
    }

    location /cgi/ {
        allowed_methods GET POST;
    }

    location /errors/ {
        allowed_methods GET;
        autoindex off;
    }
}

server {
    listen localhost:8081;
    server_name localhost local;
    root ./www;
    index index.html;
    client_max_body_size 300000000;
    autoindex off;
    error_page 404 /errors/404.html;

    location / {
        allowed_methods GET;
        index index.html;
    }

    location /assets/ {
        allowed_methods GET;
        autoindex off;
    }

    location /html/ {
        allowed_methods GET;
        autoindex off;
    }

    location /cgi/ {
        allowed_methods GET POST;
    }

    location /errors/ {
        allowed_methods GET;
        autoindex off;
    }
}
