server {
    listen localhost:8080;
    server_name localhost local;
    root www;
    index index.html;
    client_max_body_size 987654321;
    autoindex off;

    location / {
        allowed_methods GET;
        index index.html;
        client_max_body_size 145456559;
    }

    location /www {
        allowed_methods GET;
        autoindex on;
    }

    location /form {
        return 302 /test;
    }

    location /gmail {
        return 302 https://www.gmail.com/;
    }
}