server
    { 
    listen                  localhost:9743; //currently this only
    # listen                  9743; //alternative 
    server_name             localhost  alias  other_alias;
    root                    ./www;   #is_a_directory, non_exec
    index                   index.html;                  #does_page_exist
    autoindex               on;
    error_page              404 error/404.html;    #does_page_exist
    client_max_body_size    10000;                       #positive value

    location /42/bye {
        return 302 https://42kl.edu.my/;
    }

    location /cgi-demo {
        # root                    ./www;
        index                   hello.py;
        autoindex               on;
        client_max_body_size    1000;
        error_page              404 error/404.html; #does_errcode_exist, does_page_exist
        error_page              404 error/404.html; #does_errcode_exist, does_page_exist

        allowed_methods         DELETE GET POST;              #does_type_exist *
        cgi_handler             .py /usr/bin/python3;         #does_exec_exist *
        upload_store            uploads;                      #does_dir_exist
        return                  302 https://www.youtube.com/;
    }

    location /redirect {
        return 302 https://www.youtube.com/;
    }
}

server { 
    listen					localhost:8084;
    server_name				mysite.local;
    root					./www/;
    autoindex				on;
	index					index.html; #if change name to manual.html not working
    client_max_body_size	3000000;
    # client_timeout_sec 60;

    error_page				404 error/404.html;

    location / {
        allowed_methods		GET;
    }
}
