server {
    listen localhost:9743;
    server_name localhost local;
    root /Users/natalieho/Documents/Webserv/var;
    index index.html;
    client_max_body_size 30000000;
    autoindex off;
    error_page 404 error.html;

    location /42 {
        allowed_methods GET;
        index index.html;
        client_max_body_size 34;
    }

    location /42/bye {
        return 302 https://42kl.edu.my/;
    }

    location /youtube {
        return 302 https://www.youtube.com/;
    }
}

server {
    listen localhost:8080;
    server_name example;
    root /Users/natalieho/Documents/Webserv/var;
    index index.html;
    client_max_body_size 300000000;
    autoindex off;
    error_page 404 error.html;

    location / {
        allowed_methods GET;
        index index.html;
        client_max_body_size 345456789;
    }

    location /www {
        root /Users/natalieho/Documents/Webserv/var/www;
        allowed_methods GET;
    }

    location /form {
        root /Users/natalieho/Documents/Webserv/test;
        index form.html;
    }

    location /images {
        root /Users/natalieho/Documents/Webserv/images;
        allowed_methods GET;
        client_max_body_size 500098765;
        autoindex on;
        error_page 404 error.html;
    }

    location /test {
        root /Users/natalieho/Documents/Webserv/test;
        allowed_methods GET POST;
        error_page 403 error.html;
        index form.html;
    }

    location /42 {
        return 302 https://42kl.edu.my/;
    }

    location /submit {
        allowed_methods POST;
        index submit.html;
    }

    location /gmail {
        return 302 https://www.gmail.com/;
    }
}

server {
    listen localhost:8081;
    server_name localhost local;
    root /Users/natalieho/Documents/Webserv/var;
    index index.html;
    client_max_body_size 300000000;
    autoindex off;
    error_page 404 error.html;

    location / {
        allowed_methods GET;
        index index.html;
        client_max_body_size 345456789;
    }

    location /www {
        allowed_methods GET;
        autoindex on;
    }

    location /form {
        return 302 /test;
    }

    location /images {
        root /Users/natalieho/Documents/Webserv/images;
        allowed_methods GET;
        client_max_body_size 500;
        autoindex off;
        error_page 404 error.html;
    }

    location /test {
        root /Users/natalieho/Documents/Webserv/test;
        allowed_methods POST;
        error_page 403 error.html;
    }

    location /42 {
        return 302 https://42kl.edu.my/;
    }
}
