server {
	listen localhost:8080;
	server_name webserv.example.com;
	root www;
	index index_template.html;
	client_max_body_size 300000000;
	autoindex on;

	error_page 400 /error/400.html;
	error_page 403 /error/403.html;
	error_page 404 /error/404.html;
	error_page 405 /error/405.html;
	error_page 411 /error/411.html;
	error_page 413 /error/413.html;
	error_page 500 /error/500.html;

	location /t {
		alias www/html;
		index upload_result.html;
	}

	location /index {
		allowed_methods GET;
		alias www/;
		index index_template.html;
	}

	location /www {
		allowed_methods GET;
		alias www/;
		index index.html;
	}

	location /form {
		alias www/html/;
		index form.html;
	}

	location /cute/ {
		allowed_methods GET;
		alias www/asset/cat/;
		client_max_body_size 500098765;
		autoindex on;
	}

	location /img/ {
		allowed_methods GET;
		root www/asset;
		autoindex off;
	}

	location /cgi
	{
		autoindex off;
	}

	location /cgi-bin {
		allowed_methods GET POST DELETE;
		# client_max_body_size 1;
		alias www/cgi/;
		cgi_handler .py /usr/bin/python3;
		# cgi_handler .php /usr/bin/php-cgi;
		cgi_handler .php /usr/local/bin/php-cgi;
		# cgi_handler .php /opt/homebrew/bin/php-cgi;
	}

	location /test {
		allowed_methods GET;
        alias www/html/;
        index form.html;
    }

	location /calculator {
		allowed_methods GET;
		alias www/html/;
		index calculator.html;
	}

	location /filterTaskPYTHON {
		alias www/html;
		allowed_methods GET POST;
		index filterTaskPYTHON.html;
	}

	location /filterTaskPHP {
		alias www/html;
		allowed_methods GET POST;
		index filterTaskPHP.html;
	}

	location /addParcel {
		alias www/html/;
		index addParcel.html;
	}

	location /upload {
		allowed_methods GET;
		alias www/html/;
		index upload.html;
	}

	location /uploads {
		allowed_methods GET;
		autoindex on;
	}

	location /redirect {
		return 302 https://www.google.com/;
	}

	location /redirect2 {
		return 302 https://www.wetransfer.com/;
	}

	location /large-cgi {
		allowed_methods GET POST;
		client_max_body_size 1;
		cgi_handler .py /usr/bin/python3;
		alias www/cgi/;
	}

	location /large {
		allowed_methods GET POST;
		alias www/html/upload_large;
	}

	location /ico {
		alias www/asset/img;
		autoindex off;
	}
}

server {
	listen localhost:8082;
	server_name localhost local;
	root www;
	index index_8082.html;
	client_max_body_size 2000000;
	autoindex off;

	error_page 400 /error/400.html;
	error_page 403 /error/403.html;
	error_page 404 /error/404.html;
	error_page 405 /error/405.html;
	error_page 411 /error/411.html;
	error_page 413 /error/413.html;
	error_page 500 /error/500.html;

	location /login {
		allowed_methods GET;
		alias www/;
		index logIn.html;
	}

	location /cgi-bin {
		allowed_methods GET POST;
		# client_max_body_size 1;
		alias www/cgi/;
		cgi_handler .py /usr/bin/python3;
		# cgi_handler .php /usr/bin/php-cgi;
		cgi_handler .php /usr/local/bin/php-cgi;
		# cgi_handler .php /opt/homebrew/bin/php-cgi;
	}

	location /images {
		allowed_methods GET;
		alias www/asset/img/;
		autoindex on;
	}

	# test autoindex off
	location /images-off {
		allowed_methods GET;
		alias www/asset/img/;
		autoindex off;
	}

	location /ico {
		alias www/asset/img;
		autoindex off;
	}
}

server {
	listen 9743;
	server_name localhost local;
	root www;
	index index_9743.html;
	client_max_body_size 30000000;
	autoindex off;

	error_page 400 /error/400.html;
	error_page 403 /error/403.html;
	error_page 404 /error/404.html;
	error_page 405 /error/405.html;
	error_page 411 /error/411.html;
	error_page 413 /error/413.html;
	error_page 500 /error/500.html;

	location /42 {
		allowed_methods GET;
		alias www/;
		index index.html;
		client_max_body_size 34;
	}

	location /42/bye {
		return 302 https://42kl.edu.my/;
	}

	location /youtube {
		return 302 https://www.youtube.com/;
	}

	location /ico {
		alias www/asset/img;
		autoindex off;
	}
}