server {
    listen localhost:9743;
    server_name localhost local;
    root www;
    index index.html;
    client_max_body_size 3087650;
    autoindex off;
    error_page 404 error.html;

    location / {
        allowed_methods GET;
        index index.html;
        client_max_body_size 345456789;
    }

    location /cgi-bin {
        root www/cgi;        
        cgi .py /usr/bin/python3;
        cgi .php /usr/bin/php;
        allowed_methods GET POST;
    }

    location /images {
        root www/asset/img;
        allowed_methods GET;
        client_max_body_size 5000000;
        autoindex on;
        error_page 404 error.html;
    }

    location /form {
        root www/html;
        allowed_methods GET;
        index form.html;
    }

    location /42 {
        return 302 https://42kl.edu.my/;
    }
}
