server {
    listen localhost:9743;
    server_name localhost local;
    root www;
    index index.html;
    client_max_body_size 30000000;
    autoindex off;

    location /42 {
        allowed_methods GET;
        index index.html;
        client_max_body_size 34;
    }

    location /42/bye {
        return 302 https://42kl.edu.my/;
    }

    location /youtube {
        return 302 https://www.youtube.com/;
    }
}

server {
    listen localhost:8080;
    server_name example;
    root www;
    index index.html;
    client_max_body_size 300000000;
    autoindex off;

    location / {
        allowed_methods GET;
        index index.html;
        client_max_body_size 345456789;
    }

    location /www {
        index index.html;
        allowed_methods GET;
    }

    location /form {
        root www;
        index form.html;
    }

    location /cat/ {
        root www/asset/cat;
        allowed_methods GET;
        client_max_body_size 500098765;
        autoindex on;
    }

    location /cgi-bin {
        root www/cgi;
        cgi_handler .py /usr/bin/python3;
        cgi_handler .php /opt/homebrew/bin/php-cgi;
        allowed_methods GET POST;
    }

    location /test {
        root www/html;
        allowed_methods GET POST;
        index form.html;
    }

    location /submit {
        allowed_methods POST;
        index submit.html;
    }

    location /gmail {
        return 302 https://www.gmail.com/;
    }
}

server {
    listen localhost:8081;
    server_name localhost local;
    root www;
    index index.html;
    client_max_body_size 300000000;
    autoindex off;

    location / {
        allowed_methods GET;
        index index.html;
        client_max_body_size 345456789;
    }

    location /www {
        allowed_methods GET;
        autoindex on;
    }

    location /form {
        return 302 /test;
    }

    location /images {
        root www/asset/img;
        allowed_methods GET;
        client_max_body_size 500;
        autoindex off;
    }

    location /test {
        root www/html;
        allowed_methods GET;
        index form.html;
    }

    location /42 {
        return 302 https://42kl.edu.my/;
    }
}
