server {
	listen 127.0.0.1:8000;
	server_name default www.default.com;
	root www/virtual/default;
	index default.html;
}

server {
	listen 127.0.0.1:8000;
	server_name example www.example.com;
	root www/virtual/example;
	index example.html;
}

server {
	listen 127.0.0.1:8000;
	server_name test www.test.com;
	root www/virtual/test;
	index test.html;
}