server {
    host 127.0.0.1:8081;
    server_name localhost;
    root ./www;
    # autoindex on;
	index index.html;
    client_max_body_size 3000000;
    body_ram_threshold 200;
    client_timeout_sec 60;
	# client_header_buffer_size 512;

    error_page 404 /errors/404.html;

    location / {
        allowed_methods GET;
    }

    location /login {
        allowed_methods GET POST;
        index login.html;
    }

    location /api {
        allowed_methods GET;
        upload_store uploads;
    }

    location /uploads {
        allowed_methods GET POST DELETE;
        upload_store uploads;
        error_page 404 /uploads/errors/404.html;
		# autoindex on;
		# index elwhjr.html;
    }

    location /testalias {
        allowed_methods GET;
        alias var2/www2/docs/;
        index manual.html;
    }

    location /assets {
        allowed_methods GET;
    }

    location /redirect {
        return 301 /new-page.html;
    }

    location /docs {
        root var2/www2;
        index manual.html;
        autoindex on;
        allowed_methods GET;
    }

    location /cgi-bin {
        # cgi_timeout_sec 5;
        cgi .py /usr/bin/python3;
        cgi .js /usr/bin/node;
        cgi .php /usr/bin/php;
        allowed_methods GET POST;
    }
}

server {
    host 127.0.0.1:8082;
    server_name mysite.local;
    root var2/www2/docs/;
    # autoindex on;
	index manual.html;
    client_max_body_size 3000000;
    client_timeout_sec 60;
	# client_header_buffer_size 512;

    error_page 404 /errors/404.html;

    location / {
        allowed_methods GET;
    }
}


