root /var/www/; # Comments are allowed
autoindex on; # Only on and off are valid values (case ignored)

server {
    listen localhost:9743;
    server_name localhost;
    root ./assets/default_website;
    autoindex on;
    error_page 404 error_pages/404.jpg;
    cgi_handler .py /usr/bin/python3;

    location /cgi-demo {
        index hello.py;
    }
    location /redirect-demo {
        return 301 "https://www.youtube.com/watch?v=dQw4w9WgXcQ";
    }
}