server {
    listen                  localhost:9743;
    # listen                  9743; //alternative 
    server_name             localhost  alias  other_alias;
    root                    ./assets/default_website;
    index                   index.html;
    autoindex               on;
    error_page              404 error_pages/404.jpg;
    client_max_body_size    10000;

    location /cgi-demo {
        root                    var/www;
        index                   hello.py;
        autoindex               on;
        client_max_body_size    1000;
        error_page              404 /uploads/errors/404.html;

        allowed_methods         GET POST DELETE;
        cgi_handler             .py /usr/bin/python3;
        upload_store            uploads;
    }

    location /redirect-demo {
        return 301 "https://www.youtube.com/watch?v=dQw4w9WgXcQ";
    }
}

server {
    listen					127.0.0.1:8082;
    server_name				mysite.local;
    root					var2/www2/docs/;
    autoindex				on;
	index					manual.html;
    client_max_body_size	3000000;
    # client_timeout_sec 60;

    error_page				404 /errors/404.html;

    location / {
        allowed_methods		GET;
    }
}